name: daralelag
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: 2.0.7
  intl: ^0.17.0
  flutter_localizations:
    sdk: flutter
  hexcolor: ^2.0.5
  smooth_page_indicator: ^1.0.0+2
  flutter_svg: ^0.22.0
  flutter_launcher_icons: ^0.9.2
  month_picker_dialog: ^0.4.0
  date_utils: ^0.2.0
  chips_choice_null_safety: ^2.0.2
  another_flushbar: ^1.10.24
  # New packages
  provider: ^4.3.2+3
  cloud_firestore: ^1.0.6
  firebase_auth: ^1.1.1
  firebase_core: ^1.0.4
  path: ^1.7.0
  sqflite: ^1.3.1+1
  string_validator: ^0.1.4
  url_launcher: ^6.0.3
  fluttertoast: ^7.1.1
  share: ^0.6.5+4
  flushbar: ^1.10.4
  http: ^0.13.0
  flutter_sim_country_code: ^0.1.0
  google_sign_in: "^4.5.1"
  flutter_facebook_auth: "^3.5.0"
  carousel_slider: ^4.0.0
    
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/appicon.png"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_app_name: ^0.1.0
flutter_app_name:
  name: "عيادات دار العلاج"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Black.ttf
        - asset: assets/fonts/Tajawal-Bold.ttf
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
        - asset: assets/fonts/Tajawal-Light.ttf
        - asset: assets/fonts/Tajawal-Medium.ttf
        - asset: assets/fonts/Tajawal-Regular.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
